travis:
  secure:
    BINSTAR_TOKEN: ZLH/vT5LvmXWk3is9fgDwGASMCa3X02Zoa850WcTc/la5tn63a7y4/sHvHKfW9ZYOPssaO9mAXeRossGq8Q0iTgZfgmnY6+f82i8bHk4Uk8bepfzz6laSul1yQS+b70c1jLWvq1RAkdKGwlroHgmd4+VDPodHIx3tecvk+MnqFW8q/JYgmTjmmNmosbwbbxpAyaLMljVl4vBBGcIbiINBhcKFWSyW1FN7wyH20Grqu7GoJq5pfi6reOCo+49VfMEF+zIhnTH8La9+jXXoqFoN/w0k/RpmuPqgLLXAcY6lrOvM9u/mM6rgXTYdPqDiegKvu/RfvUIO2oCOlCf8zQvInrFXpOXNDf2cqiXZsjlec54/pWTZn0Z+bs0FvB6ixyN99jb7AfpkTcq78ne9RHQP9Mp2TFp3ZWtCoe2EGA7DN9XoAonyUIzjkwISTZMxvuhoaprUw9AtkG76L69gLqRv7EuyJdt9m7Euop4CToqVvSSpq6UA9SKKkMKlCLGSYb4Qq702logKZ+eRPV5gv3e/8wtrGxz0qXcVmM4saVpL27rV5ejECgMV+cwYbS19kxhISNxVR66Kah081+yqwSJ5DKRXjTjKW2LLIKaxu8Fxa+ARsPg8UpG2OBE+NU+ZZcL31GdD4opexSXgl+Dpb0/20+nlBO29wcUXPK40dBSOQE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
